/// Flutter icons PrideIcons
/// Copyright (C) 2019 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// 
/// 
///
import 'package:flutter/widgets.dart';

class PrideIcons {
  PrideIcons._();

  static const _kFontFam = 'PrideIcons';

  static const IconData ic_1 = const IconData(0xe800, fontFamily: _kFontFam);
  static const IconData ic_2 = const IconData(0xe801, fontFamily: _kFontFam);
  static const IconData ic_3 = const IconData(0xe802, fontFamily: _kFontFam);
}
